# Generated by Django 3.2 on 2021-05-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deck", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="theme",
            field=models.CharField(
                choices=[
                    ("black", "black"),
                    ("beige", "beige"),
                    ("blood", "blood"),
                    ("league", "league"),
                    ("moon", "moon"),
                    ("night", "night"),
                    ("serif", "serif"),
                    ("simple", "simple"),
                    ("sky", "sky"),
                    ("solarized", "solarized"),
                    ("white", "white"),
                ],
                default="simple",
                max_length=256,
            ),
        ),
    ]
